### ISSUE TITLE
Are the models actually published?

### ISSUE THREAD

**Issue by EvanKrall** [Cydral/AI-Image-Denoiser#1]
The README says:

> Our model has also been published directly on the official [Dlib models repository](https://github.com/davisking/dlib-models).

I don't see any model files in that repo that seem to relate to denoising. Am I missing something?

**Comment by Cydral** [comment]
We have not yet published a model, as the results obtained did not seem convincing enough to be adopted by the community. However, a model will most likely be published by mid-year.
